import { FlatCompat } from '@eslint/eslintrc';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import unusedImports from 'eslint-plugin-unused-imports';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    plugins: { 'jsx-a11y': jsxA11y, 'unused-imports': unusedImports },
    rules: {
      ...jsxA11y.flatConfigs.recommended.rules,
      // @typescript-eslint/no-unused-vars flags an unused import but has no
      // fixer (removing a symbol from a multi-symbol import statement is
      // riskier to automate than a whole-import removal). unused-imports'
      // version supports --fix for exactly that case; unused-imports handles
      // imports, no-unused-vars (still active) keeps covering locals/args.
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'warn',
        { vars: 'all', varsIgnorePattern: '^_', args: 'after-used', argsIgnorePattern: '^_' }
      ]
    }
  },
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'src/lib/firebase/rules.emulator.test.ts',
      // Auto-regenerated by `next dev`/`next build` on every run and already
      // gitignored — not a file to hand-edit or hold to lint rules.
      'next-env.d.ts'
    ]
  }
];

export default eslintConfig;
